language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: bPKzj4waWiJY9fnOFOcBhLrZ6sn4/yIuKfprOOU9SDFOFdSGVTw/zL0Ju1PL+SWL/dwrs8xkmUccEZ8SzCdVD5K0IuCWIV5URU7vKj8ujha/Vcglbx3zy1C7HHyrTqywZWswoCu1CB89hp4JOBbG9lFLoTqI1/rbdGnCLTiVnqGJ64bZU629UbbglU7AZ+Yt1GmwKna5dTkTYaVBWNUag7Aj4OYnQrRZ6rI9e2VSJak5yC8H3D6ttjxGKXHY+dkt/TFoQS0ryAJ57Kjb9276bN8FxeEIjuzgMon6KlTa2eb8D4d4Gs1w1xmGeEAqwiJ8vn7gg1zaWVw/LT5Mp7MxabbQ89sLvmubIVhFXXG1vqwS5+/Glshoru0cqeS/e1gdMTC1LxRrnq1FmCanQPgr3gvoGrn0h+nVYFxPWKiD3bvpzGmS0tbJAyTHr73dIZYwPI+4CW459Jx6KE2b2mcHPQav7OYsa7HRkFfGWU7vV3fiRYDusEoR0deVI//z0oIZIHRrs6cLT5vZkYjIXy1P1S84eBcYLqxT5M3eXXAL2Wdtdgwp1chr3Z+kCt3EN6ASHLhhvHkwg6Kp0eBNfN34iOEAqt7levIp9x3z9zeFthScW76WRXRbvfgv2Am5FvtyVs7rhNsTPkEWR0dt0ez3VAgi05usRU/vhgwH5WBEF5U=
  email: false
