const reply = {
  'statusCode': '200',
  'body': 'ok',
  'headers': [ 'Content-Type',
  'text/html',
  'Transfer-Encoding',
  'chunked',
  'Connection',
  'close',
  'Date',
  'Sat, 10 Feb 2018 17:19:46 GMT',
  'Server',
  'Apache',
  'Vary',
  'Accept-Encoding',
  'X-Slack-Backend',
  'h',
  'Referrer-Policy',
  'no-referrer',
  'Strict-Transport-Security',
  'max-age=31536000; includeSubDomains; preload',
  'X-Frame-Options',
  'SAMEORIGIN',
  'Access-Control-Allow-Origin',
  '*',
  'X-Via',
  'haproxy-lb-www-1m79',
  'X-Cache',
  'Miss from cloudfront',
  'Via',
  '1.1 9a75cc11971085fc36bff426f03899e0.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id',
  '9UIb1oAn3CHYCN_3VynRSYWN2x4VAr8bcwPQyBtcZWoYEG7QwfPVmQ==' ] 
}

module.exports = reply;
